
package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DbConnection", targetNamespace = "http://services.product.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DbConnection {


    /**
     * 
     * @param prodID
     * @return
     *     returns com.ArrayOfXsdAnyType
     */
    @WebMethod(operationName = "SelectProduct")
    @WebResult(name = "SelectProductReturn", targetNamespace = "http://services.product.com")
    @RequestWrapper(localName = "SelectProduct", targetNamespace = "http://services.product.com", className = "com.SelectProduct")
    @ResponseWrapper(localName = "SelectProductResponse", targetNamespace = "http://services.product.com", className = "com.SelectProductResponse")
    public ArrayOfXsdAnyType selectProduct(
        @WebParam(name = "ProdID", targetNamespace = "http://services.product.com")
        String prodID);

}
