
package com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DbConnectionService", targetNamespace = "http://services.product.com", wsdlLocation = "file:/C:/Users/Pavithra/IdeaProjects/ECOM/product-data-access/src/main/java/com/services/product/data/access_c1/wsdl/DbConnection.wsdl")
public class DbConnectionService
    extends Service
{

    private final static URL DBCONNECTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBCONNECTIONSERVICE_EXCEPTION;
    private final static QName DBCONNECTIONSERVICE_QNAME = new QName("http://services.product.com", "DbConnectionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Pavithra/IdeaProjects/ECOM/product-data-access/src/main/java/com/services/product/data/access_c1/wsdl/DbConnection.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBCONNECTIONSERVICE_WSDL_LOCATION = url;
        DBCONNECTIONSERVICE_EXCEPTION = e;
    }

    public DbConnectionService() {
        super(__getWsdlLocation(), DBCONNECTIONSERVICE_QNAME);
    }

    public DbConnectionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBCONNECTIONSERVICE_QNAME, features);
    }

    public DbConnectionService(URL wsdlLocation) {
        super(wsdlLocation, DBCONNECTIONSERVICE_QNAME);
    }

    public DbConnectionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBCONNECTIONSERVICE_QNAME, features);
    }

    public DbConnectionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DbConnectionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DbConnection
     */
    @WebEndpoint(name = "DbConnection")
    public DbConnection getDbConnection() {
        return super.getPort(new QName("http://services.product.com", "DbConnection"), DbConnection.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DbConnection
     */
    @WebEndpoint(name = "DbConnection")
    public DbConnection getDbConnection(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.product.com", "DbConnection"), DbConnection.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBCONNECTIONSERVICE_EXCEPTION!= null) {
            throw DBCONNECTIONSERVICE_EXCEPTION;
        }
        return DBCONNECTIONSERVICE_WSDL_LOCATION;
    }

}
